apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image-task
spec:
  params:
    - name: IMAGE
      type: string
      description: "The image name to build and push (e.g. your-registry.io/ml-tekton-katib:latest)"
  workspaces:
  - name: source
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--dockerfile=$(workspaces.source.path)/Dockerfile"
      - "--context=$(workspaces.source.path)"
      - "--destination=$(params.IMAGE)"
      - "--insecure"
      # 如果仓库需要认证，也需要通过Secret/ServiceAccount指定credentials
