# tekton/tasks/build-image-task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image-task
spec:
  params:
    - name: IMAGE
      type: string
      description: "The image name:tag to build and push, e.g. docker.io/hirschazer/kubeflow_ci:latest"
  workspaces:
    - name: source
      description: "Workspace containing Dockerfile, code"
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace/source
      args:
        - "--dockerfile=Dockerfile"
        - "--context=/workspace/source"
        - "--destination=$(params.IMAGE)"
      # 如果需要私有仓库, 确保已在集群创建 docker-registry Secret 并绑定 ServiceAccount
