# tekton/tasks/build-image-task.yaml

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image-task
spec:
  params:
    - name: IMAGE
      type: string
      description: "The image name:tag to build and push, e.g. docker.io/hirschazer/kubeflow_ci:latest"
  workspaces:
    - name: source
      description: "Workspace that contains the Dockerfile and project code"
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace/source
      args:
        - "--dockerfile=Dockerfile"
        - "--context=/workspace/source"
        - "--destination=$(params.IMAGE)"
        # 如需不校验仓库TLS可加 --skip-tls-verify --insecure
        #   - "--skip-tls-verify=true"
        #   - "--insecure"

