# kubeflow_ci/tekton/tasks/git-clone-task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: url
      type: string
      description: "Git repository URL to clone"
    - name: revision
      type: string
      default: "master"
  workspaces:
    - name: source
      description: The workspace where to clone the repo
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/usr/bin/env sh
        git init
        git remote add origin "$(params.url)"
        git fetch --all --prune  # 拉取最新分支并清理旧分支
        git reset --hard origin/$(params.revision)  # 强制同步到最新代码
        ls -al
      workingDir: /workspace/source

