# tekton/tasks/train-with-best-params.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: train-with-best-params
spec:
  params:
    - name: BEST_LR
      type: string
      default: "0.001"
    - name: BEST_BS
      type: string
      default: "32"
  workspaces:
    - name: source
    - name: data
  steps:
    - name: final-train
      # 指定我们构建好的镜像
      image: "docker.io/hirschazer/kubeflow_ci:latest"
      script: |
        #!/usr/bin/env bash
        echo "Final training with LR=$(params.BEST_LR), BS=$(params.BEST_BS)"
        python /app/scripts/train_final.py $(params.BEST_LR) $(params.BEST_BS)

        # /workspace/model/model.pt 是保存好的模型
        # 这里可以加把模型上传到MinIO的步骤
