# kubeflow_ci/tekton/tasks/train-with-best-params.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: train-with-best-params
spec:
  params:
    - name: BEST_LR
      type: string
      default: "0.001"
    - name: BEST_BS
      type: string
      default: "32"

  workspaces:
    - name: source
      description: "Workspace containing the training code"
    - name: data
      description: "Workspace containing data"

  steps:
    - name: final-train
      image: docker.io/hirschazer/kubeflow_ci:latest
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        echo "=== Final training with best hyperparams ==="
        echo "LR: $(params.BEST_LR), BS: $(params.BEST_BS)"

        # train_final.py <learning_rate> <batch_size>
        python scripts/train_final.py $(params.BEST_LR) $(params.BEST_BS)

        echo "=== Checking data volume ==="
        ls -al /workspace/data

        echo "=== Final training completed ==="
