# kubeflow_ci/tekton/pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-image-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: data-workspace

  params:
    - name: git-url
      type: string
      default: "https://github.com/Epochex/kubeflow_ci.git"
    - name: git-revision
      type: string
      default: "master"
    - name: image-url
      type: string
      default: "docker.io/hirschazer/kubeflow_ci:latest"
    - name: katib-experiment-file
      type: string
      default: "katib/katib-experiment.yaml"

  tasks:
    - name: pvc-consumer
      taskSpec:
        steps:
          - name: check-pvc
            image: busybox
            script: |
              #!/bin/sh
              echo "PVC mounted at /workspace/source:"
              ls -al /workspace/source
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: git-clone
      runAfter:
        - pvc-consumer
      taskRef:
        name: git-clone-task
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-image
      runAfter:
        - git-clone
      taskRef:
        name: build-image-task
      params:
        - name: IMAGE
          value: "$(params.image-url)"
      workspaces:
        - name: source
          workspace: shared-workspace

    # 新增: run-katib
    - name: run-katib
      runAfter:
        - build-image
      taskRef:
        name: run-katib-task
      params:
        - name: KATIB_EXPERIMENT_FILE
          value: "$(params.katib-experiment-file)"

    # 新增: train-with-best-params
    - name: train-with-best-params
      runAfter:
        - run-katib
      taskRef:
        name: train-with-best-params
      params:
        - name: BEST_LR
          value: "$(tasks.run-katib.results.best-learning-rate)"
        - name: BEST_BS
          value: "$(tasks.run-katib.results.best-batch-size)"
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: data
          workspace: data-workspace


# runAfter: [build-image]：表示先要构建并推送训练镜像，再做 Katib 超参调优。
# train-with-best-params 依赖 run-katib，并通过 $(tasks.run-katib.results.best-learning-rate) 获取 Katib 结果。
# train-with-best-params 也需要 data-workspace，用来加载 CSV 数据，写路径 /workspace/data/xxx.csv