# kubeflow_ci/tekton/pipeline-run.yaml

# 如果没有创建就解注释apply
# 1) PVC 定义
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard # 指定默认 StorageClass
---

# 2) PipelineRun 定义
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-image-run
spec:
  # 这里指定 SA，Tekton 会给所有 task 默认使用这个 SA
  serviceAccountName: pipeline

  pipelineRef:
    name: build-image-pipeline

  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: ci-pvc
    - name: data-workspace
      emptyDir: {}
  params:
    - name: git-url
      value: "https://github.com/Epochex/kubeflow_ci.git"
    - name: git-revision
      value: "master"
    - name: image-url
      value: "docker.io/hirschazer/kubeflow_ci:latest"
    - name: katib-experiment-file
      value: "katib/katib-experiment.yaml"






