# tekton/pipeline.yaml

# 这样一个最小 Pipeline，执行时只需要给它提供：
# 一个Workspace（里面有 Dockerfile、项目代码）；
# image-url 参数；
# 就能完成镜像的 build & push

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-image-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: image-url
      type: string
      description: "Full Docker image path, e.g. docker.io/hirschazer/kubeflow_ci:latest"
      default: "docker.io/hirschazer/kubeflow_ci:latest"
  tasks:
    - name: build-image
      taskRef:
        name: build-image-task
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "$(params.image-url)"

