# kubeflow_ci/tekton/triggers.yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: mlops-pipeline-template
spec:
  params:
    - name: git-repo
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: mlops-pipeline-run-
      spec:
        pipelineRef:
          name: mlops-pipeline
        workspaces:
          - name: shared-workspace
            emptyDir: {}   # 这里可以指定 emptyDir
          - name: data-workspace
            emptyDir: {}
        params:
          - name: git-url
            value: "$(params.git-repo)"
          - name: git-revision
            value: "$(params.git-revision)"
          - name: image-url
            value: "docker.io/hirschazer/kubeflow_ci:latest"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: mlops-pipeline-triggerbinding
spec:
  params:
    - name: git-repo
      value: "$(body.repository.clone_url)"
    - name: git-revision
      value: "$(body.head_commit.id)"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: mlops-pipeline-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: mlops-pipeline-trigger
      bindings:
        - ref: mlops-pipeline-triggerbinding
      template:
        ref: mlops-pipeline-template
