apiVersion: v1
kind: Pod
metadata:
  name: test-image-pull
  namespace: default
spec:
  containers:
    - name: test-container
      image: docker.io/hirschazer/kubeflow_ci:latest
  imagePullSecrets:
    - name: docker-cred
